version: '3'

services:
  api:
    build:
      context: ./docker/api
    volumes:
      - .:/app
    ports:
      - 8000:80
    command: bash -c "composer install && php -S 0.0.0.0:80 public/index.php"

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-example}
      MYSQL_USER: ${DB_USER:-user}
      MYSQL_PASS: ${DB_PASSWORD:-example}
    volumes:
      - ./dbdata:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8080:8080
